name: tosspayments_widget_sdk_flutter
version: 2.1.1

environment:
  sdk: '>=3.8.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.0
  tosspayments_webview_flutter: ^1.0.6
  url_launcher: ^6.0.10
  os_info_plugin: ^0.0.1
  flutter_inappwebview: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0